# Generated by Django 5.0.1 on 2024-02-21 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Info',
        ),
        migrations.AlterModelTable(
            name='info',
            table='info',
        ),
    ]
