# Generated by Django 5.0.1 on 2024-02-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
