# Generated by Django 5.0.1 on 2024-03-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermodule', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.TextField()),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('fish', 'Fish'), ('rabbit', 'Rabbit'), ('parrot', 'Parrot'), ('goat', 'Goat'), ('horse', 'Horse')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
