# Generated by Django 5.0.1 on 2024-03-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='petbooking',
            table='petbookinfo',
        ),
    ]
