# Generated by Django 5.0.1 on 2024-04-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0004_alter_petbooking_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField(max_length=50)),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_breed', models.CharField(max_length=100)),
                ('pet_age', models.IntegerField()),
                ('return_reason', models.TextField()),
                ('return_date', models.DateField()),
            ],
        ),
    ]
